_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.13.2
        t:
            "1":
                - 1
                - 41
                - 55
            "2":
                - 1
                - 41
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.13.2
            "5": 0.19.8
            "8":
                - 3
                - 5
            "12": 0.19.8
            "13": windows-amd64
artifact_alias:
    value: latest
batch_size:
    value: 16
bbox_interval:
    value: -1
bucket:
    value: ""
cache:
    value: null
cfg:
    value: ""
cos_lr:
    value: false
data:
    value: data\coco.yaml
data_dict:
    value:
        download: bash ./scripts/get_coco.sh
        names:
            "0": person
            "1": bicycle
            "2": car
            "3": motorcycle
            "4": airplane
            "5": bus
            "6": train
            "7": truck
            "8": boat
            "9": traffic light
            "10": fire hydrant
            "11": stop sign
            "12": parking meter
            "13": bench
            "14": bird
            "15": cat
            "16": dog
            "17": horse
            "18": sheep
            "19": cow
            "20": elephant
            "21": bear
            "22": zebra
            "23": giraffe
            "24": backpack
            "25": umbrella
            "26": handbag
            "27": tie
            "28": suitcase
            "29": frisbee
            "30": skis
            "31": snowboard
            "32": sports ball
            "33": kite
            "34": baseball bat
            "35": baseball glove
            "36": skateboard
            "37": surfboard
            "38": tennis racket
            "39": bottle
            "40": wine glass
            "41": cup
            "42": fork
            "43": knife
            "44": spoon
            "45": bowl
            "46": banana
            "47": apple
            "48": sandwich
            "49": orange
            "50": broccoli
            "51": carrot
            "52": hot dog
            "53": pizza
            "54": donut
            "55": cake
            "56": chair
            "57": couch
            "58": potted plant
            "59": bed
            "60": dining table
            "61": toilet
            "62": tv
            "63": laptop
            "64": mouse
            "65": remote
            "66": keyboard
            "67": cell phone
            "68": microwave
            "69": oven
            "70": toaster
            "71": sink
            "72": refrigerator
            "73": book
            "74": clock
            "75": vase
            "76": scissors
            "77": teddy bear
            "78": hair drier
            "79": toothbrush
        nc: 80
        test: C:\Users\trapx\Desktop\yolov7-segmentation-main\coco\test-dev2017.txt
        train: C:\Users\trapx\Desktop\yolov7-segmentation-main\coco\train2017.txt
        val: C:\Users\trapx\Desktop\yolov7-segmentation-main\coco\val2017.txt
device:
    value: ""
entity:
    value: null
epochs:
    value: 300
evolve:
    value: null
exist_ok:
    value: false
freeze:
    value:
        - 0
hyp:
    value:
        anchor_t: 4
        box: 0.05
        cls: 0.5
        cls_pw: 1
        copy_paste: 0
        degrees: 0
        fl_gamma: 0
        fliplr: 0.5
        flipud: 0
        hsv_h: 0.015
        hsv_s: 0.7
        hsv_v: 0.4
        iou_t: 0.2
        lr0: 0.01
        lrf: 0.01
        mixup: 0
        momentum: 0.937
        mosaic: 1
        obj: 1
        obj_pw: 1
        perspective: 0
        scale: 0.5
        shear: 0
        translate: 0.1
        warmup_bias_lr: 0.1
        warmup_epochs: 3
        warmup_momentum: 0.8
        weight_decay: 0.0005
image_weights:
    value: false
imgsz:
    value: 640
label_smoothing:
    value: 0
local_rank:
    value: -1
multi_scale:
    value: false
name:
    value: exp
noautoanchor:
    value: false
noplots:
    value: false
nosave:
    value: false
noval:
    value: false
optimizer:
    value: SGD
patience:
    value: 100
project:
    value: runs\train
quad:
    value: false
rect:
    value: false
resume:
    value: false
save_dir:
    value: runs\train\exp
save_period:
    value: -1
seed:
    value: 0
single_cls:
    value: false
sync_bn:
    value: false
upload_dataset:
    value: false
weights:
    value: yolov5s.pt
workers:
    value: 8
